-- Generated from data/srd-5-1/*.json
-- Run after 001_initial_schema.sql and 003_content_sources_seed.sql

insert into species (owner_user_id, source_id, visibility, slug, name, summary, description, size, base_speed, languages, subspecies_slugs, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'elfo', 'Elfo', 'Especie agil y perceptiva, asociada con sentidos agudos y entrenamiento natural.', 'Seed inicial para validar el eje species-subspecies del catalogo. La modelizacion completa de rasgos puede ampliarse mas adelante.', 'medium', 30, array['comun', 'elfico']::text[], array['high-elf', 'wood-elf']::text[], '[{"type":"ability_bonus","ability":"dexterity","value":2},{"type":"speed","value":30},{"type":"darkvision","range":60},{"type":"language","mode":"fixed","language":"comun"},{"type":"language","mode":"fixed","language":"elfico"},{"type":"proficiency","proficiencyType":"skill","value":"perception"},{"type":"note","text":"Advantage on saving throws against being charmed, and magic cannot put you to sleep."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'humano', 'Humano', 'Versatil y adaptable, con mejoras generales de caracteristica.', 'Seed inicial basada en la documentacion SRD del proyecto. Conviene revisar nombres y redaccion final contra la fuente oficial antes de ampliar el catalogo.', 'medium', 30, array['comun', 'choose:any:1']::text[], '{}'::text[], '[{"type":"ability_bonus","ability":"strength","value":1},{"type":"ability_bonus","ability":"dexterity","value":1},{"type":"ability_bonus","ability":"constitution","value":1},{"type":"ability_bonus","ability":"intelligence","value":1},{"type":"ability_bonus","ability":"wisdom","value":1},{"type":"ability_bonus","ability":"charisma","value":1},{"type":"speed","value":30},{"type":"language","mode":"fixed","language":"comun"},{"type":"choose_language","count":1}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'enano', 'Enano', 'Especie resistente y disciplinada, asociada con fortaleza, tradicion y sentidos agudos bajo tierra.', 'Entrada canonica ampliada para reforzar la cobertura del creador guiado con una especie robusta del SRD.', 'medium', 25, array['comun', 'dwarfico']::text[], array['hill-dwarf', 'mountain-dwarf']::text[], '[{"type":"ability_bonus","ability":"constitution","value":2},{"type":"speed","value":25},{"type":"darkvision","range":60},{"type":"language","mode":"fixed","language":"comun"},{"type":"language","mode":"fixed","language":"dwarfico"},{"type":"resistance","damageType":"poison"},{"type":"note","text":"You have advantage on saving throws against poison."},{"type":"note","text":"Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mediano', 'Mediano', 'Especie pequena y resolutiva, marcada por su suerte, agilidad y valentia inesperada.', 'Entrada canonica ampliada para incorporar una especie pequena del SRD con rasgos sociales y defensivos distintivos.', 'small', 25, array['comun', 'halfling']::text[], array['lightfoot-halfling', 'stout-halfling']::text[], '[{"type":"ability_bonus","ability":"dexterity","value":2},{"type":"speed","value":25},{"type":"language","mode":"fixed","language":"comun"},{"type":"language","mode":"fixed","language":"halfling"},{"type":"note","text":"When you roll a 1 on the d20 for an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll."},{"type":"note","text":"You have advantage on saving throws against being frightened."},{"type":"note","text":"You can move through the space of any creature that is of a size larger than yours."}]'::jsonb, true)
on conflict do nothing;

insert into subspecies (owner_user_id, source_id, visibility, species_slug, slug, name, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'elfo', 'high-elf', 'High Elf', 'Subespecie elfica con entrenamiento adicional y aptitud magica.', 'Seed inicial para validar la relacion species-subspecies dentro del catalogo. El contenido detallado puede ampliarse mas adelante.', '[{"type":"ability_bonus","ability":"intelligence","value":1},{"type":"proficiency","proficiencyType":"weapon","value":"longsword"},{"type":"proficiency","proficiencyType":"weapon","value":"shortsword"},{"type":"proficiency","proficiencyType":"weapon","value":"shortbow"},{"type":"proficiency","proficiencyType":"weapon","value":"longbow"},{"type":"choose_language","count":1},{"type":"note","text":"Gain one wizard cantrip of your choice."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'elfo', 'wood-elf', 'Wood Elf', 'Subespecie elfica agil y sigilosa, adaptada a territorios salvajes.', 'Seed inicial para ampliar la cobertura del catalogo species-subspecies con una variante orientada a movilidad y exploracion.', '[{"type":"ability_bonus","ability":"wisdom","value":1},{"type":"speed","value":35},{"type":"note","text":"You can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'enano', 'hill-dwarf', 'Hill Dwarf', 'Subespecie enana perseverante, sabia y especialmente resistente a la fatiga.', 'Entrada canonica ampliada para reforzar la rama de enanos con una opcion orientada a aguante y tradicion.', '[{"type":"ability_bonus","ability":"wisdom","value":1},{"type":"note","text":"Your hit point maximum increases by 1, and it increases by 1 every time you gain a level."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'enano', 'mountain-dwarf', 'Mountain Dwarf', 'Subespecie enana de complexon poderosa, entrenada para la guerra y el uso de armaduras.', 'Entrada canonica ampliada para reforzar la cobertura marcial del creador guiado con una variante enana robusta.', '[{"type":"ability_bonus","ability":"strength","value":2},{"type":"proficiency","proficiencyType":"armor","value":"light-armor"},{"type":"proficiency","proficiencyType":"armor","value":"medium-armor"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mediano', 'lightfoot-halfling', 'Lightfoot Halfling', 'Subespecie mediana afable y discreta, con talento natural para pasar desapercibida.', 'Entrada canonica ampliada para cubrir una variante social y sigilosa de los medianos.', '[{"type":"ability_bonus","ability":"charisma","value":1},{"type":"note","text":"You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mediano', 'stout-halfling', 'Stout Halfling', 'Subespecie mediana resistente y sobria, notable por su aguante frente a toxinas.', 'Entrada canonica ampliada para cubrir una variante mediana defensiva con resistencia adicional.', '[{"type":"ability_bonus","ability":"constitution","value":1},{"type":"resistance","damageType":"poison"},{"type":"note","text":"You have advantage on saving throws against poison."}]'::jsonb, true)
on conflict do nothing;

insert into character_classes (owner_user_id, source_id, visibility, slug, name, hit_die, primary_abilities, saving_throw_proficiencies, armor_proficiencies, weapon_proficiencies, tool_proficiencies, skill_choices, starting_equipment, spellcasting_ability, progression, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guerrero', 'Guerrero', 10, array['strength', 'dexterity']::text[], array['strength', 'constitution']::text[], array['all-armor', 'shields']::text[], array['simple-weapons', 'martial-weapons']::text[], '{}'::text[], '{"count":2,"options":["acrobatics","animal-handling","athletics","history","insight","intimidation","perception","survival"]}'::jsonb, '[{"type":"item","id":"chain-mail"},{"type":"choice","options":["martial-weapon-and-shield","two-martial-weapons"]},{"type":"choice","options":["light-crossbow-and-20-bolts","two-handaxes"]},{"type":"choice","options":["dungeoneers-pack","explorers-pack"]}]'::jsonb, null, '[{"level":1,"features":["fighting-style","second-wind"]}]'::jsonb, 'Clase marcial versatil enfocada en armas, armaduras y resistencia.', 'Seed inicial basada en la documentacion SRD del proyecto. Conviene contrastar la redaccion final con la fuente oficial antes de poblar mas niveles y opciones.', '[{"type":"proficiency","proficiencyType":"armor","value":"all-armor"},{"type":"proficiency","proficiencyType":"armor","value":"shields"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"weapon","value":"martial-weapons"},{"type":"proficiency","proficiencyType":"saving_throw","value":"strength"},{"type":"proficiency","proficiencyType":"saving_throw","value":"constitution"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["acrobatics","animal-handling","athletics","history","insight","intimidation","perception","survival"]},{"type":"feature","featureId":"fighting-style"},{"type":"feature","featureId":"second-wind"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'clerigo', 'Clerigo', 8, array['wisdom']::text[], array['wisdom', 'charisma']::text[], array['light-armor', 'medium-armor', 'shields']::text[], array['simple-weapons']::text[], '{}'::text[], '{"count":2,"options":["history","insight","medicine","persuasion","religion"]}'::jsonb, '[{"type":"choice","options":["mace","warhammer"],"note":"Warhammer requires martial weapon proficiency."},{"type":"choice","options":["scale-mail","leather-armor","chain-mail"],"note":"Chain mail requires proficiency."},{"type":"choice","options":["light-crossbow-and-20-bolts","any-simple-weapon"]},{"type":"choice","options":["priests-pack","explorers-pack"]},{"type":"item","id":"shield"},{"type":"item","id":"holy-symbol"}]'::jsonb, 'wisdom', '[{"level":1,"features":["spellcasting","divine-domain"]},{"level":2,"features":["channel-divinity","divine-domain-feature"]}]'::jsonb, 'Clase divina que combina magia de apoyo, curacion y presencia marcial basica.', 'Seed inicial basada en reglas basicas oficiales. La preparacion completa de conjuros y dominios se modelara de forma incremental.', '[{"type":"proficiency","proficiencyType":"armor","value":"light-armor"},{"type":"proficiency","proficiencyType":"armor","value":"medium-armor"},{"type":"proficiency","proficiencyType":"armor","value":"shields"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"saving_throw","value":"wisdom"},{"type":"proficiency","proficiencyType":"saving_throw","value":"charisma"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["history","insight","medicine","persuasion","religion"]},{"type":"spellcasting","ability":"wisdom"},{"type":"feature","featureId":"spellcasting"},{"type":"feature","featureId":"divine-domain"},{"type":"feature","featureId":"channel-divinity"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mago', 'Mago', 6, array['intelligence']::text[], array['intelligence', 'wisdom']::text[], '{}'::text[], array['dagger', 'dart', 'sling', 'quarterstaff', 'light-crossbow']::text[], '{}'::text[], '{"count":2,"options":["arcana","history","insight","investigation","medicine","religion"]}'::jsonb, '[{"type":"choice","options":["quarterstaff","any-simple-weapon"]},{"type":"item","id":"spellbook"},{"type":"choice","options":["explorers-pack","dungeoneers-pack"]},{"type":"item","id":"satchel"}]'::jsonb, 'intelligence', '[{"level":1,"features":["spellcasting","arcane-recovery"]},{"level":2,"features":["arcane-tradition"]}]'::jsonb, 'Clase arcana centrada en estudio, preparacion y control flexible del repertorio de conjuros.', 'Seed inicial basada en reglas basicas oficiales. La progresion completa del grimorio y las escuelas se ampliara de forma incremental.', '[{"type":"proficiency","proficiencyType":"weapon","value":"dagger"},{"type":"proficiency","proficiencyType":"weapon","value":"dart"},{"type":"proficiency","proficiencyType":"weapon","value":"sling"},{"type":"proficiency","proficiencyType":"weapon","value":"quarterstaff"},{"type":"proficiency","proficiencyType":"weapon","value":"light-crossbow"},{"type":"proficiency","proficiencyType":"saving_throw","value":"intelligence"},{"type":"proficiency","proficiencyType":"saving_throw","value":"wisdom"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["arcana","history","insight","investigation","medicine","religion"]},{"type":"spellcasting","ability":"intelligence"},{"type":"feature","featureId":"spellcasting"},{"type":"feature","featureId":"arcane-recovery"},{"type":"feature","featureId":"arcane-tradition"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'picaro', 'Picaro', 8, array['dexterity']::text[], array['dexterity', 'intelligence']::text[], array['light-armor']::text[], array['simple-weapons', 'hand-crossbow', 'longsword', 'rapier', 'shortsword']::text[], array['thieves-tools']::text[], '{"count":4,"options":["acrobatics","athletics","deception","insight","intimidation","investigation","perception","performance","persuasion","sleight-of-hand","stealth"]}'::jsonb, '[{"type":"choice","options":["rapier","shortsword"]},{"type":"choice","options":["shortbow-and-20-arrows","shortsword"]},{"type":"choice","options":["burglars-pack","dungeoneers-pack","explorers-pack"]},{"type":"item","id":"leather-armor"},{"type":"item","id":"dagger","quantity":2},{"type":"item","id":"thieves-tools"}]'::jsonb, null, '[{"level":1,"features":["expertise","sneak-attack","thieves-cant"]},{"level":2,"features":["cunning-action"]},{"level":3,"features":["roguish-archetype"]}]'::jsonb, 'Clase agil y oportunista, experta en sigilo, precision y habilidades utilitarias.', 'Entrada canonica ampliada para cubrir una clase de nivel 1 muy relevante para el creador guiado y con elecciones claras de equipo y habilidades.', '[{"type":"proficiency","proficiencyType":"armor","value":"light-armor"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"weapon","value":"hand-crossbow"},{"type":"proficiency","proficiencyType":"weapon","value":"longsword"},{"type":"proficiency","proficiencyType":"weapon","value":"rapier"},{"type":"proficiency","proficiencyType":"weapon","value":"shortsword"},{"type":"proficiency","proficiencyType":"tool","value":"thieves-tools"},{"type":"proficiency","proficiencyType":"saving_throw","value":"dexterity"},{"type":"proficiency","proficiencyType":"saving_throw","value":"intelligence"},{"type":"choose_proficiency","proficiencyType":"skill","count":4,"options":["acrobatics","athletics","deception","insight","intimidation","investigation","perception","performance","persuasion","sleight-of-hand","stealth"]},{"type":"feature","featureId":"expertise"},{"type":"feature","featureId":"sneak-attack"},{"type":"feature","featureId":"thieves-cant"},{"type":"feature","featureId":"cunning-action"},{"type":"feature","featureId":"roguish-archetype"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'barbaro', 'Barbaro', 12, array['strength', 'constitution']::text[], array['strength', 'constitution']::text[], array['light-armor', 'medium-armor', 'shields']::text[], array['simple-weapons', 'martial-weapons']::text[], '{}'::text[], '{"count":2,"options":["animal-handling","athletics","intimidation","nature","perception","survival"]}'::jsonb, '[{"type":"choice","options":["greataxe","martial-melee-weapon"]},{"type":"choice","options":["two-handaxes","any-simple-weapon"]},{"type":"item","id":"explorers-pack"},{"type":"item","id":"four-javelins"}]'::jsonb, null, '[{"level":1,"features":["rage","unarmored-defense"]},{"level":2,"features":["reckless-attack","danger-sense"]},{"level":3,"features":["primal-path"]}]'::jsonb, 'Clase marcial feroz basada en resistencia fisica, furia y asaltos contundentes.', 'Entrada canonica ampliada para cubrir una clase base del SRD centrada en supervivencia y combate directo sin dependencia de conjuros.', '[{"type":"proficiency","proficiencyType":"armor","value":"light-armor"},{"type":"proficiency","proficiencyType":"armor","value":"medium-armor"},{"type":"proficiency","proficiencyType":"armor","value":"shields"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"weapon","value":"martial-weapons"},{"type":"proficiency","proficiencyType":"saving_throw","value":"strength"},{"type":"proficiency","proficiencyType":"saving_throw","value":"constitution"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["animal-handling","athletics","intimidation","nature","perception","survival"]},{"type":"feature","featureId":"rage"},{"type":"feature","featureId":"unarmored-defense"},{"type":"feature","featureId":"reckless-attack"},{"type":"feature","featureId":"danger-sense"},{"type":"feature","featureId":"primal-path"}]'::jsonb, true)
on conflict do nothing;

insert into subclasses (owner_user_id, source_id, visibility, class_slug, slug, name, summary, description, granted_spells_by_level, features, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'clerigo', 'life-domain', 'Life Domain', 'Dominio clerical centrado en curacion, vitalidad y proteccion de la vida.', 'Seed inicial derivado de reglas basicas oficiales. Mantener la redaccion mecanica breve y ampliar solo tras validar el modelo del catalogo.', '[{"level":1,"spellSlugs":["bless","cure-wounds"]},{"level":3,"spellSlugs":["lesser-restoration","spiritual-weapon"]},{"level":5,"spellSlugs":["beacon-of-hope","revivify"]},{"level":7,"spellSlugs":["death-ward","guardian-of-faith"]},{"level":9,"spellSlugs":["mass-cure-wounds","raise-dead"]}]'::jsonb, '[{"level":1,"featureId":"bonus-proficiency","name":"Bonus Proficiency","summary":"Ganas competencia con armadura pesada.","mechanics":[{"type":"proficiency","proficiencyType":"armor","value":"heavy-armor"}]},{"level":1,"featureId":"disciple-of-life","name":"Disciple of Life","summary":"Tus conjuros de curacion recuperan puntos de golpe adicionales.","mechanics":[{"type":"note","text":"When you use a spell of 1st level or higher to restore hit points, add 2 + the spell level."}]},{"level":2,"featureId":"preserve-life","name":"Channel Divinity: Preserve Life","summary":"Canalizas energia curativa para repartir puntos de golpe entre criaturas cercanas.","mechanics":[{"type":"note","text":"Restore hit points equal to five times your cleric level, divided among creatures within 30 feet, up to half their maximum hit points."}]}]'::jsonb, '[{"type":"spell_grant","spellId":"bless"},{"type":"spell_grant","spellId":"cure-wounds"},{"type":"spell_grant","spellId":"lesser-restoration"},{"type":"spell_grant","spellId":"spiritual-weapon"},{"type":"spell_grant","spellId":"beacon-of-hope"},{"type":"spell_grant","spellId":"revivify"},{"type":"spell_grant","spellId":"death-ward"},{"type":"spell_grant","spellId":"guardian-of-faith"},{"type":"spell_grant","spellId":"mass-cure-wounds"},{"type":"spell_grant","spellId":"raise-dead"},{"type":"proficiency","proficiencyType":"armor","value":"heavy-armor"},{"type":"feature","featureId":"bonus-proficiency"},{"type":"feature","featureId":"disciple-of-life"},{"type":"feature","featureId":"preserve-life"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mago', 'school-of-evocation', 'School of Evocation', 'Escuela arcana enfocada en modelar energia destructiva sin perder control tactico.', 'Seed inicial derivado de reglas basicas oficiales. Mantener el detalle mecanico breve hasta ampliar la cobertura de escuelas y rasgos de clase.', '[]'::jsonb, '[{"level":2,"featureId":"evocation-savant","name":"Evocation Savant","summary":"Copias conjuros de evocacion en tu grimorio con menos tiempo y coste.","mechanics":[{"type":"note","text":"The gold and time you must spend to copy an evocation spell into your spellbook is halved."}]},{"level":2,"featureId":"sculpt-spells","name":"Sculpt Spells","summary":"Proteges a aliados elegidos del pleno impacto de tus conjuros de evocacion.","mechanics":[{"type":"note","text":"When you cast an evocation spell that affects other creatures you can see, choose creatures equal to 1 + the spell''s level to automatically succeed on their saving throws and take no damage on a successful save."}]}]'::jsonb, '[{"type":"feature","featureId":"evocation-savant"},{"type":"feature","featureId":"sculpt-spells"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'clerigo', 'knowledge-domain', 'Knowledge Domain', 'Dominio clerical enfocado en aprendizaje sagrado, memoria y acceso a saberes ocultos.', 'Seed inicial derivado de reglas basicas oficiales. Esta entrada amplia la cobertura de conjuros concedidos por subclase y mantiene los rasgos resumidos hasta completar mas niveles.', '[{"level":1,"spellSlugs":["command","identify"]},{"level":3,"spellSlugs":["augury","suggestion"]},{"level":5,"spellSlugs":["nondetection","speak-with-dead"]},{"level":7,"spellSlugs":["arcane-eye","confusion"]},{"level":9,"spellSlugs":["legend-lore","scrying"]}]'::jsonb, '[{"level":1,"featureId":"blessings-of-knowledge","name":"Blessings of Knowledge","summary":"Aprendes idiomas adicionales y ganas una pericia orientada al conocimiento.","mechanics":[{"type":"note","text":"You learn two languages of your choice and become proficient in two of Arcana, History, Nature, or Religion."}]},{"level":2,"featureId":"knowledge-of-the-ages","name":"Channel Divinity: Knowledge of the Ages","summary":"Invocas comprension divina para dominar temporalmente una habilidad o herramienta.","mechanics":[{"type":"note","text":"As an action, choose one skill or tool; for 10 minutes, you have proficiency with the chosen skill or tool."}]},{"level":6,"featureId":"read-thoughts","name":"Channel Divinity: Read Thoughts","summary":"Percibes pensamientos superficiales y puedes dirigir la mente de un objetivo con magia.","mechanics":[{"type":"note","text":"You can read a creature''s surface thoughts and may cast Suggestion on it without expending a spell slot."}]}]'::jsonb, '[{"type":"spell_grant","spellId":"command"},{"type":"spell_grant","spellId":"identify"},{"type":"spell_grant","spellId":"augury"},{"type":"spell_grant","spellId":"suggestion"},{"type":"spell_grant","spellId":"nondetection"},{"type":"spell_grant","spellId":"speak-with-dead"},{"type":"spell_grant","spellId":"arcane-eye"},{"type":"spell_grant","spellId":"confusion"},{"type":"spell_grant","spellId":"legend-lore"},{"type":"spell_grant","spellId":"scrying"},{"type":"feature","featureId":"blessings-of-knowledge"},{"type":"feature","featureId":"knowledge-of-the-ages"},{"type":"feature","featureId":"read-thoughts"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guerrero', 'champion', 'Champion', 'Arquetipo marcial enfocado en precision atletica, resistencia y excelencia fisica.', 'Seed inicial derivado de reglas basicas oficiales. Esta entrada amplia la cobertura de subclases no lanzadoras de conjuros con rasgos marciales sencillos.', '[]'::jsonb, '[{"level":3,"featureId":"improved-critical","name":"Improved Critical","summary":"Tus golpes arma consiguen impactos criticos con mayor frecuencia.","mechanics":[{"type":"note","text":"Your weapon attacks score a critical hit on a roll of 19 or 20."}]},{"level":7,"featureId":"remarkable-athlete","name":"Remarkable Athlete","summary":"Tu destreza fisica mejora saltos, empujes y pruebas atleticas no dominadas.","mechanics":[{"type":"note","text":"Add half your proficiency bonus to Strength, Dexterity, and Constitution checks you are not already proficient in, and increase your running long jump distance."}]},{"level":10,"featureId":"additional-fighting-style","name":"Additional Fighting Style","summary":"Adoptas un segundo estilo de combate para reforzar tu especializacion marcial.","mechanics":[{"type":"note","text":"You can choose a second option from the Fighting Style class feature."}]}]'::jsonb, '[{"type":"feature","featureId":"improved-critical"},{"type":"feature","featureId":"remarkable-athlete"},{"type":"feature","featureId":"additional-fighting-style"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'picaro', 'thief', 'Thief', 'Arquetipo de picaro centrado en manos rapidas, movilidad y dominio de la infiltracion.', 'Entrada canonica ampliada para dar cobertura a una subclase clasica del SRD sin dependencias de conjuros.', '[]'::jsonb, '[{"level":3,"featureId":"fast-hands","name":"Fast Hands","summary":"Aprovechas tu accion adicional para tareas de manos rapidas y juego sucio utilitario.","mechanics":[{"type":"note","text":"You can use the bonus action granted by Cunning Action to make a Dexterity (Sleight of Hand) check, use thieves'' tools to disarm a trap or open a lock, or take the Use an Object action."}]},{"level":3,"featureId":"second-story-work","name":"Second-Story Work","summary":"Escalas y saltas con soltura poco comun entre aventureros.","mechanics":[{"type":"note","text":"Climbing no longer costs you extra movement, and your running jump distance increases by a number of feet equal to your Dexterity modifier."}]},{"level":9,"featureId":"supreme-sneak","name":"Supreme Sneak","summary":"Tu sigilo mejora notablemente cuando avanzas con cautela.","mechanics":[{"type":"note","text":"You have advantage on a Dexterity (Stealth) check if you move no more than half your speed on the same turn."}]},{"level":13,"featureId":"use-magic-device","name":"Use Magic Device","summary":"Improvisas con objetos magicos incluso cuando normalmente no serias apto para usarlos.","mechanics":[{"type":"note","text":"You ignore all class, race, and level requirements on the use of magic items."}]},{"level":17,"featureId":"thiefs-reflexes","name":"Thief''s Reflexes","summary":"Actuas con una rapidez excepcional al inicio del combate.","mechanics":[{"type":"note","text":"You can take two turns during the first round of any combat, taking your first turn at your normal initiative and your second turn at your initiative minus 10."}]}]'::jsonb, '[{"type":"feature","featureId":"fast-hands"},{"type":"feature","featureId":"second-story-work"},{"type":"feature","featureId":"supreme-sneak"},{"type":"feature","featureId":"use-magic-device"},{"type":"feature","featureId":"thiefs-reflexes"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'barbaro', 'berserker', 'Berserker', 'Camino barbaro orientado a una furia desatada que sacrifica control por agresion implacable.', 'Entrada canonica ampliada para dar cobertura a una subclase barbarica basica del SRD sin mecanicas de lanzamiento de conjuros.', '[]'::jsonb, '[{"level":3,"featureId":"frenzy","name":"Frenzy","summary":"Tu rabia puede convertirse en un estado aun mas feroz a cambio de agotamiento posterior.","mechanics":[{"type":"note","text":"While raging, you can choose to frenzy; if you do, you can make a single melee weapon attack as a bonus action on each of your turns after this one, and you suffer one level of exhaustion when your rage ends."}]},{"level":6,"featureId":"mindless-rage","name":"Mindless Rage","summary":"Tu furia te blinda frente a ciertos efectos mentales mientras permanece activa.","mechanics":[{"type":"note","text":"You can''t be charmed or frightened while raging; if you are charmed or frightened when you enter your rage, the effect is suspended for the duration of the rage."}]},{"level":10,"featureId":"intimidating-presence","name":"Intimidating Presence","summary":"Tu sola presencia puede quebrar la voluntad de un enemigo cercano.","mechanics":[{"type":"note","text":"As an action, choose one creature within 30 feet that can see or hear you; it must succeed on a Wisdom saving throw or be frightened of you until the end of your next turn."}]},{"level":14,"featureId":"retaliation","name":"Retaliation","summary":"Respondes de inmediato a quienes se atreven a herirte en combate cercano.","mechanics":[{"type":"note","text":"When you take damage from a creature within 5 feet of you, you can use your reaction to make a melee weapon attack against that creature."}]}]'::jsonb, '[{"type":"feature","featureId":"frenzy"},{"type":"feature","featureId":"mindless-rage"},{"type":"feature","featureId":"intimidating-presence"},{"type":"feature","featureId":"retaliation"}]'::jsonb, true)
on conflict do nothing;

insert into backgrounds (owner_user_id, source_id, visibility, slug, name, skill_proficiencies, tool_proficiencies, languages, equipment, feature_name, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'acolyte', 'Acolyte', array['insight', 'religion']::text[], '{}'::text[], array['choose:any:2']::text[], '[{"type":"item","id":"holy-symbol"},{"type":"choice","options":["prayer-book","prayer-wheel"]},{"type":"item","id":"sticks-of-incense","quantity":5},{"type":"item","id":"vestments"},{"type":"item","id":"common-clothes"},{"type":"item","id":"belt-pouch","note":"Contains 15 gp."}]'::jsonb, 'Shelter of the Faithful', 'Trasfondo religioso centrado en estudio, rituales y apoyo de una comunidad de fe.', 'Seed inicial del SRD para disponer de un trasfondo reutilizable en formularios y futuras pantallas de contenido.', '[{"type":"proficiency","proficiencyType":"skill","value":"insight"},{"type":"proficiency","proficiencyType":"skill","value":"religion"},{"type":"choose_language","count":2},{"type":"note","text":"Can receive healing and care at temples that share your faith, and may call on priests for modest assistance."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'soldier', 'Soldier', array['athletics', 'intimidation']::text[], array['gaming-set', 'vehicles-land']::text[], '{}'::text[], '[{"type":"item","id":"insignia-of-rank"},{"type":"item","id":"trophy-from-a-fallen-enemy"},{"type":"choice","options":["bone-dice","cards"]},{"type":"item","id":"common-clothes"},{"type":"item","id":"belt-pouch","note":"Contains 10 gp."}]'::jsonb, 'Military Rank', 'Trasfondo marcial que aporta disciplina, experiencia militar y reconocimiento entre tropas.', 'Seed inicial del SRD para representar competencias y rasgos sociales reutilizables.', '[{"type":"proficiency","proficiencyType":"skill","value":"athletics"},{"type":"proficiency","proficiencyType":"skill","value":"intimidation"},{"type":"proficiency","proficiencyType":"tool","value":"gaming-set"},{"type":"proficiency","proficiencyType":"tool","value":"vehicles-land"},{"type":"note","text":"Soldiers loyal to your former military organization still recognize your authority and influence."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'criminal', 'Criminal', array['deception', 'stealth']::text[], array['thieves-tools', 'gaming-set']::text[], '{}'::text[], '[{"type":"item","id":"crowbar"},{"type":"item","id":"dark-common-clothes"},{"type":"item","id":"belt-pouch","note":"Contains 15 gp."}]'::jsonb, 'Criminal Contact', 'Trasfondo urbano y clandestino que aporta engaño, sigilo y contactos dentro del hampa.', 'Entrada canonica ampliada para cubrir uno de los trasfondos mas utiles del SRD en combinacion con personajes orientados a sigilo.', '[{"type":"proficiency","proficiencyType":"skill","value":"deception"},{"type":"proficiency","proficiencyType":"skill","value":"stealth"},{"type":"proficiency","proficiencyType":"tool","value":"thieves-tools"},{"type":"proficiency","proficiencyType":"tool","value":"gaming-set"},{"type":"note","text":"You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'noble', 'Noble', array['history', 'persuasion']::text[], array['gaming-set']::text[], array['choose:any:1']::text[], '[{"type":"item","id":"fine-clothes"},{"type":"item","id":"signet-ring"},{"type":"item","id":"parchment-scroll"},{"type":"item","id":"belt-pouch","note":"Contains 25 gp."}]'::jsonb, 'Position of Privilege', 'Trasfondo social de alta cuna que aporta educacion, influencia y reconocimiento cortesano.', 'Entrada canonica ampliada para cubrir un trasfondo de interaccion social fuerte dentro del SRD.', '[{"type":"proficiency","proficiencyType":"skill","value":"history"},{"type":"proficiency","proficiencyType":"skill","value":"persuasion"},{"type":"proficiency","proficiencyType":"tool","value":"gaming-set"},{"type":"choose_language","count":1},{"type":"note","text":"People are inclined to think the best of you, and common folk make every effort to accommodate you and avoid your displeasure."}]'::jsonb, true)
on conflict do nothing;

insert into spells (owner_user_id, source_id, visibility, slug, name, level, school, casting_time, range_text, components, materials, duration, concentration, ritual, class_slugs, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guidance', 'Guidance', 0, 'divination', '1 action', 'Touch', 'V, S', null, 'Concentration, up to 1 minute', true, false, array['clerigo']::text[], 'Una criatura suma 1d4 a una prueba de caracteristica antes de que termine el conjuro.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'light', 'Light', 0, 'evocation', '1 action', 'Touch', 'V, M', 'A firefly or phosphorescent moss.', '1 hour', false, false, array['mago']::text[], 'Un objeto tocado emite luz brillante y tenue durante una hora.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mage-hand', 'Mage Hand', 0, 'conjuration', '1 action', '30 feet', 'V, S', null, '1 minute', false, false, array['mago']::text[], 'Creas una mano espectral para manipular objetos a distancia.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'ray-of-frost', 'Ray of Frost', 0, 'evocation', '1 action', '60 feet', 'V, S', null, 'Instantaneous', false, false, array['mago']::text[], 'Un rayo helado inflige dano por frio y reduce la velocidad del objetivo.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'sacred-flame', 'Sacred Flame', 0, 'evocation', '1 action', '60 feet', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Una llama radiante obliga a una salvacion de destreza e inflige dano radiante.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'spare-the-dying', 'Spare the Dying', 0, 'necromancy', '1 action', 'Touch', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Una criatura moribunda se estabiliza sin recuperar puntos de golpe.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'thaumaturgy', 'Thaumaturgy', 0, 'transmutation', '1 action', '30 feet', 'V', null, 'Up to 1 minute', false, false, array['clerigo']::text[], 'Manifiestas pequenos prodigios sobrenaturales como voces potentes, temblores o puertas que se abren.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'bless', 'Bless', 1, 'enchantment', '1 action', '30 feet', 'V, S, M', 'A sprinkling of holy water.', 'Up to 1 minute', true, false, array['clerigo']::text[], 'Hasta tres criaturas suman 1d4 a tiradas de ataque y salvacion.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'detect-magic', 'Detect Magic', 1, 'divination', '1 action', 'Self', 'V, S', null, 'Concentration, up to 10 minutes', true, true, array['mago']::text[], 'Percibes magia cercana y la escuela vinculada a efectos visibles.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'command', 'Command', 1, 'enchantment', '1 action', '60 feet', 'V', null, '1 round', false, false, array['clerigo']::text[], 'Pronuncias una orden de una sola palabra que una criatura debe obedecer en su siguiente turno.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'cure-wounds', 'Cure Wounds', 1, 'evocation', '1 action', 'Touch', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Una criatura que tocas recupera puntos de golpe.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guiding-bolt', 'Guiding Bolt', 1, 'evocation', '1 action', '120 feet', 'V, S', null, '1 round', false, false, array['clerigo']::text[], 'Un destello radiante hiere al objetivo y concede ventaja al siguiente ataque contra el.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'identify', 'Identify', 1, 'divination', '1 minute', 'Touch', 'V, S, M', 'A pearl worth at least 100 gp and an owl feather.', 'Instantaneous', false, true, array['mago']::text[], 'Revelas propiedades magicas de un objeto o efecto tocado.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mage-armor', 'Mage Armor', 1, 'abjuration', '1 action', 'Touch', 'V, S, M', 'A piece of cured leather.', '8 hours', false, false, array['mago']::text[], 'Una criatura sin armadura gana una proteccion magica que mejora su clase de armadura.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'magic-missile', 'Magic Missile', 1, 'evocation', '1 action', '120 feet', 'V, S', null, 'Instantaneous', false, false, array['mago']::text[], 'Dardos de fuerza golpean automaticamente y pueden repartirse entre varios objetivos.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'lesser-restoration', 'Lesser Restoration', 2, 'abjuration', '1 action', 'Touch', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Elimina una enfermedad o una condicion de una criatura.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'augury', 'Augury', 2, 'divination', '1 minute', 'Self', 'V, S, M', 'Specially marked sticks, bones, or similar tokens worth at least 25 gp.', 'Instantaneous', false, true, array['clerigo']::text[], 'Recibes un presagio sobre el resultado inmediato de un curso de accion concreto.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'spiritual-weapon', 'Spiritual Weapon', 2, 'evocation', '1 bonus action', '60 feet', 'V, S', null, '1 minute', false, false, array['clerigo']::text[], 'Creas un arma espectral que ataca como accion adicional.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'suggestion', 'Suggestion', 2, 'enchantment', '1 action', '30 feet', 'V, M', 'A snake''s tongue and either a bit of honeycomb or a drop of sweet oil.', 'Concentration, up to 8 hours', true, false, array['mago']::text[], 'Influyes con una frase razonable en la conducta de una criatura que pueda oirte y entenderte.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'beacon-of-hope', 'Beacon of Hope', 3, 'abjuration', '1 action', '30 feet', 'V, S', null, 'Up to 1 minute', true, false, array['clerigo']::text[], 'Las criaturas elegidas ganan ventaja a sabiduria y muerte, y reciben curacion maxima.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'revivify', 'Revivify', 3, 'necromancy', '1 action', 'Touch', 'V, S, M', 'Diamonds worth 300 gp, which the spell consumes.', 'Instantaneous', false, false, array['clerigo']::text[], 'Devuelve a la vida a una criatura muerta hace poco.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'nondetection', 'Nondetection', 3, 'abjuration', '1 action', 'Touch', 'V, S, M', 'A pinch of diamond dust worth 25 gp sprinkled over the target, which the spell consumes.', '8 hours', false, false, array['mago']::text[], 'Oculta a una criatura u objeto frente a adivinacion y sensores magicos.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'speak-with-dead', 'Speak with Dead', 3, 'necromancy', '1 action', '10 feet', 'V, S, M', 'Burning incense.', '10 minutes', false, false, array['clerigo']::text[], 'Concedes una apariencia de vida e intelecto a un cadaver para hacerle preguntas limitadas.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'death-ward', 'Death Ward', 4, 'abjuration', '1 action', 'Touch', 'V, S', null, '8 hours', false, false, array['clerigo']::text[], 'Protege a una criatura contra un golpe mortal o un efecto letal.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'arcane-eye', 'Arcane Eye', 4, 'divination', '1 action', '30 feet', 'V, S, M', 'A bit of bat fur.', 'Concentration, up to 1 hour', true, false, array['mago']::text[], 'Creas un ojo invisible que explora a distancia y transmite vision.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'confusion', 'Confusion', 4, 'enchantment', '1 action', '90 feet', 'V, S, M', 'Three nut shells.', 'Concentration, up to 1 minute', true, false, array['mago']::text[], 'Alteras la mente de varias criaturas para volverlas erraticas e impredecibles.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guardian-of-faith', 'Guardian of Faith', 4, 'conjuration', '1 action', '30 feet', 'V', null, '8 hours', false, false, array['clerigo']::text[], 'Un guardian espectral inflige dano radiante a enemigos cercanos.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mass-cure-wounds', 'Mass Cure Wounds', 5, 'evocation', '1 action', '60 feet', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Varias criaturas elegidas recuperan puntos de golpe.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'legend-lore', 'Legend Lore', 5, 'divination', '10 minutes', 'Self', 'V, S, M', 'Incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each.', 'Instantaneous', false, false, array['mago']::text[], 'Recibes saberes legendarios sobre una persona, lugar u objeto importante.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'raise-dead', 'Raise Dead', 5, 'necromancy', '1 hour', 'Touch', 'V, S, M', 'A diamond worth at least 500 gp, which the spell consumes.', 'Instantaneous', false, false, array['clerigo']::text[], 'Devuelve a la vida a una criatura fallecida hace no demasiado tiempo.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'scrying', 'Scrying', 5, 'divination', '10 minutes', 'Self', 'V, S, M', 'A focus worth at least 1,000 gp, such as a crystal ball, silver mirror, or font filled with holy water.', 'Concentration, up to 10 minutes', true, false, array['mago']::text[], 'Observas a una criatura concreta mediante un sensor invisible cercano a ella.', null, '[]'::jsonb, true)
on conflict do nothing;

insert into feats (owner_user_id, source_id, visibility, slug, name, prerequisites, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'athlete', 'Athlete', '{}'::text[], 'Mejora la capacidad fisica general y agiliza varios movimientos atleticos.', 'Seed inicial del SRD para representar una dote con mejora flexible de fuerza o destreza y notas de movilidad.', '[{"type":"choose_ability_bonus","count":1,"value":1,"allowed":["strength","dexterity"]},{"type":"note","text":"Standing up from prone uses only 5 feet of movement."},{"type":"note","text":"Climbing no longer costs extra movement, and you can make a running long jump or high jump after moving only 5 feet."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'heavily-armored', 'Heavily Armored', array['proficiency:armor:medium-armor']::text[], 'Entrenamiento adicional para usar armadura pesada.', 'Seed inicial del SRD para disponer de una dote centrada en competencia defensiva y mejora de caracteristica.', '[{"type":"ability_bonus","ability":"strength","value":1},{"type":"proficiency","proficiencyType":"armor","value":"heavy-armor"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'keen-mind', 'Keen Mind', '{}'::text[], 'Aumenta la agudeza mental y la capacidad de orientacion y recuerdo.', 'Seed inicial del SRD para disponer de una dote centrada en inteligencia y memoria excepcional.', '[{"type":"ability_bonus","ability":"intelligence","value":1},{"type":"note","text":"You always know which way is north and how many hours remain before the next sunrise or sunset."},{"type":"note","text":"You can accurately recall anything you have seen or heard within the past month."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'resilient-constitution', 'Resilient (Constitution)', '{}'::text[], 'Refuerza la resistencia fisica y otorga competencia en salvaciones de constitucion.', 'Seed inicial del SRD para ampliar la familia de dotes de resiliencia con una opcion util para concentracion y aguante.', '[{"type":"ability_bonus","ability":"constitution","value":1},{"type":"proficiency","proficiencyType":"saving_throw","value":"constitution"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'resilient-wisdom', 'Resilient (Wisdom)', '{}'::text[], 'Refuerza la voluntad y otorga competencia en salvaciones de sabiduria.', 'Seed inicial del SRD para representar una dote orientada a caracteristicas y tiradas de salvacion.', '[{"type":"ability_bonus","ability":"wisdom","value":1},{"type":"proficiency","proficiencyType":"saving_throw","value":"wisdom"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'observant', 'Observant', '{}'::text[], 'Aumenta la percepcion de detalles y la lectura de labios.', 'Seed inicial del SRD para representar una dote con mejora flexible de inteligencia o sabiduria y observacion reforzada.', '[{"type":"choose_ability_bonus","count":1,"value":1,"allowed":["intelligence","wisdom"]},{"type":"note","text":"You can read lips if you can see a creature''s mouth while it is speaking a language you understand."},{"type":"note","text":"You gain a +5 bonus to passive Wisdom (Perception) and passive Intelligence (Investigation)."}]'::jsonb, true)
on conflict do nothing;

insert into equipment (owner_user_id, source_id, visibility, slug, name, category, summary, description, weight, value, damage, damage_type, range_text, properties, is_weapon, is_equippable, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'any-simple-weapon', 'Any Simple Weapon', 'choice-bundle', 'Placeholder reference for any simple weapon choice.', null, null, null, null, null, null, '{}'::text[], true, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'artisan-tools', 'Artisan''s Tools', 'tool', 'General artisan tool set.', null, null, '15 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'belt-pouch', 'Belt Pouch', 'container', 'A small pouch worn at the waist.', null, 1, '5 sp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'bone-dice', 'Bone Dice', 'gaming-set', 'A simple gaming set of carved dice.', null, null, '1 sp', null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'burglars-pack', 'Burglar''s Pack', 'pack', 'A pack suited to infiltration, climbing, and illicit entry.', null, 46, '16 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'cards', 'Playing Cards', 'gaming-set', 'A deck of playing cards.', null, null, '5 sp', null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'chain-mail', 'Chain Mail', 'armor', 'Heavy armor made from interlocking metal rings.', null, 55, '75 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'common-clothes', 'Common Clothes', 'clothing', 'Plain everyday clothing.', null, 3, '5 sp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'crowbar', 'Crowbar', 'adventuring-gear', 'A solid iron lever useful for forcing open stuck objects.', null, 5, '2 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'dagger', 'Dagger', 'weapon', 'A light finesse blade that can be thrown.', null, 1, '2 gp', '1d4', 'piercing', '20/60 ft.', array['finesse', 'light', 'thrown']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'dark-common-clothes', 'Dark Common Clothes', 'clothing', 'Dark, practical common clothes suited to staying unnoticed.', null, 3, '5 sp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'dungeoneers-pack', 'Dungeoneer''s Pack', 'pack', 'A pack stocked for underground exploration.', null, 61, '12 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'explorers-pack', 'Explorer''s Pack', 'pack', 'A travel pack for overland adventuring.', null, 59, '10 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'fine-clothes', 'Fine Clothes', 'clothing', 'Well-made clothing suited to courtly or upper-class life.', null, 6, '15 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'four-javelins', 'Four Javelins', 'bundle', 'A small bundle of four throwing spears.', null, 8, '2 gp', '1d6', 'piercing', '30/120 ft.', array['thrown', 'versatile (1d8)']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'greataxe', 'Greataxe', 'weapon', 'A heavy martial melee weapon.', null, 7, '30 gp', '1d12', 'slashing', 'Melee', array['heavy', 'two-handed']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'holy-symbol', 'Holy Symbol', 'focus', 'A divine focus representing a deity.', null, 1, '5 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'insignia-of-rank', 'Insignia of Rank', 'trinket', 'A military insignia marking prior service.', null, null, null, null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'lantern', 'Lantern', 'adventuring-gear', 'A hooded lantern for steady light.', null, 2, '5 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'leather-armor', 'Leather Armor', 'armor', 'Light armor made from cured leather.', null, 10, '10 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'light-crossbow-and-20-bolts', 'Light Crossbow and 20 Bolts', 'bundle', 'A ranged weapon bundle with ammunition.', null, 6, '26 gp', '1d8', 'piercing', '80/320 ft.', array['ammunition', 'loading', 'two-handed']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'parchment-scroll', 'Parchment Scroll', 'document', 'A sealed or rolled parchment document.', null, null, '1 sp', null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mace', 'Mace', 'weapon', 'A simple melee weapon with a sturdy head.', null, 4, '5 gp', '1d6', 'bludgeoning', 'Melee', '{}'::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'martial-weapon-and-shield', 'Martial Weapon and Shield', 'bundle', 'Reference bundle for a martial weapon paired with a shield.', null, null, null, null, null, null, '{}'::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'martial-melee-weapon', 'Martial Melee Weapon', 'choice-bundle', 'Reference choice for any martial melee weapon.', null, null, null, null, null, null, '{}'::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'prayer-book', 'Prayer Book', 'book', 'A devotional text used in worship and ritual.', null, 5, '1 gp', null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'prayer-wheel', 'Prayer Wheel', 'focus', 'A small rotating devotional focus.', null, 1, '1 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'priests-pack', 'Priest''s Pack', 'pack', 'A support pack used by clerics and temple servants.', null, 24, '19 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'quarterstaff', 'Quarterstaff', 'weapon', 'A simple wooden staff usable as a melee weapon.', null, 4, '2 sp', '1d6', 'bludgeoning', 'Melee', array['versatile (1d8)']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'rapier', 'Rapier', 'weapon', 'A finesse martial melee weapon favored by duelists.', null, 2, '25 gp', '1d8', 'piercing', 'Melee', array['finesse']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'satchel', 'Satchel', 'container', 'A shoulder-worn bag for books and notes.', null, 2, '1 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'scale-mail', 'Scale Mail', 'armor', 'Medium armor of overlapping metal scales.', null, 45, '50 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'shield', 'Shield', 'armor', 'A defensive shield carried in one hand.', null, 6, '10 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'smith-tools', 'Smith''s Tools', 'tool', 'A smithing tool set for forging and repair.', null, 8, '20 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'spellbook', 'Spellbook', 'book', 'A wizard''s spellbook containing prepared formulae.', null, 3, '50 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'shortbow-and-20-arrows', 'Shortbow and 20 Arrows', 'bundle', 'A shortbow paired with a basic supply of arrows.', null, 3, '26 gp', '1d6', 'piercing', '80/320 ft.', array['ammunition', 'two-handed']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'shortsword', 'Shortsword', 'weapon', 'A light finesse blade suited to quick strikes.', null, 2, '10 gp', '1d6', 'piercing', 'Melee', array['finesse', 'light']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'signet-ring', 'Signet Ring', 'jewelry', 'A ring bearing a family or official seal.', null, null, '5 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'sticks-of-incense', 'Sticks of Incense', 'consumable', 'A bundle of incense used in prayer and ritual.', null, null, null, null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'thieves-tools', 'Thieves'' Tools', 'tool', 'A compact set of picks, files, and other tools for locks and traps.', null, 1, '25 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'travelers-clothes', 'Traveler''s Clothes', 'clothing', 'Durable clothes for long roads.', null, 4, '2 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'trophy-from-a-fallen-enemy', 'Trophy From a Fallen Enemy', 'trinket', 'A keepsake taken from a defeated foe.', null, null, null, null, null, null, '{}'::text[], false, false, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'two-handaxes', 'Two Handaxes', 'bundle', 'A pair of light axes for close combat or throwing.', null, 4, '1 gp', '1d6', 'slashing', '20/60 ft.', array['light', 'thrown']::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'two-martial-weapons', 'Two Martial Weapons', 'choice-bundle', 'Reference bundle for choosing two martial weapons.', null, null, null, null, null, null, '{}'::text[], true, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'vestments', 'Vestments', 'clothing', 'Ceremonial robes for religious service.', null, 4, '2 gp', null, null, null, '{}'::text[], false, true, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'warhammer', 'Warhammer', 'weapon', 'A martial melee weapon with crushing force.', null, 2, '15 gp', '1d8', 'bludgeoning', 'Melee', array['versatile (1d10)']::text[], true, true, '[]'::jsonb, true)
on conflict do nothing;

