-- Generated from data/srd-5-1/*.json
-- Run after 001_initial_schema.sql and 003_content_sources_seed.sql
-- Recommended before 002_initial_rls_policies.sql if you want initial catalog
-- rows to exist before enabling and testing policies.

insert into species (owner_user_id, source_id, visibility, slug, name, summary, description, size, base_speed, languages, subspecies_slugs, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'elfo', 'Elfo', 'Especie agil y perceptiva, asociada con sentidos agudos y entrenamiento natural.', 'Seed inicial para validar el eje species-subspecies del catalogo. La modelizacion completa de rasgos puede ampliarse mas adelante.', 'medium', 30, array['comun', 'elfico']::text[], array['high-elf']::text[], '[{"type":"ability_bonus","ability":"dexterity","value":2},{"type":"speed","value":30},{"type":"darkvision","range":60},{"type":"language","mode":"fixed","language":"comun"},{"type":"language","mode":"fixed","language":"elfico"},{"type":"proficiency","proficiencyType":"skill","value":"perception"},{"type":"note","text":"Advantage on saving throws against being charmed, and magic cannot put you to sleep."}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'humano', 'Humano', 'Versatil y adaptable, con mejoras generales de caracteristica.', 'Seed inicial basada en la documentacion SRD del proyecto. Conviene revisar nombres y redaccion final contra la fuente oficial antes de ampliar el catalogo.', 'medium', 30, array['comun']::text[], '{}'::text[], '[{"type":"ability_bonus","ability":"strength","value":1},{"type":"ability_bonus","ability":"dexterity","value":1},{"type":"ability_bonus","ability":"constitution","value":1},{"type":"ability_bonus","ability":"intelligence","value":1},{"type":"ability_bonus","ability":"wisdom","value":1},{"type":"ability_bonus","ability":"charisma","value":1},{"type":"speed","value":30},{"type":"language","mode":"fixed","language":"comun"},{"type":"choose_language","count":1}]'::jsonb, true)
on conflict do nothing;

insert into subspecies (owner_user_id, source_id, visibility, species_slug, slug, name, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'elfo', 'high-elf', 'High Elf', 'Subespecie elfica con entrenamiento adicional y aptitud magica.', 'Seed inicial para validar la relacion species-subspecies dentro del catalogo. El contenido detallado puede ampliarse mas adelante.', '[{"type":"ability_bonus","ability":"intelligence","value":1},{"type":"proficiency","proficiencyType":"weapon","value":"longsword"},{"type":"proficiency","proficiencyType":"weapon","value":"shortsword"},{"type":"proficiency","proficiencyType":"weapon","value":"shortbow"},{"type":"proficiency","proficiencyType":"weapon","value":"longbow"},{"type":"choose_language","count":1},{"type":"note","text":"Gain one wizard cantrip of your choice."}]'::jsonb, true)
on conflict do nothing;

insert into character_classes (owner_user_id, source_id, visibility, slug, name, hit_die, primary_abilities, saving_throw_proficiencies, armor_proficiencies, weapon_proficiencies, tool_proficiencies, skill_choices, starting_equipment, spellcasting_ability, progression, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guerrero', 'Guerrero', 10, array['strength', 'dexterity']::text[], array['strength', 'constitution']::text[], array['all-armor', 'shields']::text[], array['simple-weapons', 'martial-weapons']::text[], '{}'::text[], '{"count":2,"options":["acrobatics","animal-handling","athletics","history","insight","intimidation","perception","survival"]}'::jsonb, '["chain-mail","martial-weapon-and-shield-or-two-martial-weapons","light-crossbow-and-20-bolts-or-two-handaxes","dungeoneers-pack-or-explorers-pack"]'::jsonb, null, '[{"level":1,"features":["fighting-style","second-wind"]}]'::jsonb, 'Clase marcial versatil enfocada en armas, armaduras y resistencia.', 'Seed inicial basada en la documentacion SRD del proyecto. Conviene contrastar la redaccion final con la fuente oficial antes de poblar mas niveles y opciones.', '[{"type":"proficiency","proficiencyType":"armor","value":"all-armor"},{"type":"proficiency","proficiencyType":"armor","value":"shields"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"weapon","value":"martial-weapons"},{"type":"proficiency","proficiencyType":"saving_throw","value":"strength"},{"type":"proficiency","proficiencyType":"saving_throw","value":"constitution"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["acrobatics","animal-handling","athletics","history","insight","intimidation","perception","survival"]},{"type":"feature","featureId":"fighting-style"},{"type":"feature","featureId":"second-wind"}]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'clerigo', 'Clerigo', 8, array['wisdom']::text[], array['wisdom', 'charisma']::text[], array['light-armor', 'medium-armor', 'shields']::text[], array['simple-weapons']::text[], '{}'::text[], '{"count":2,"options":["history","insight","medicine","persuasion","religion"]}'::jsonb, '["mace-or-warhammer-if-proficient","scale-mail-or-leather-armor-or-chain-mail-if-proficient","light-crossbow-and-20-bolts-or-any-simple-weapon","priests-pack-or-explorers-pack","shield","holy-symbol"]'::jsonb, 'wisdom', '[{"level":1,"features":["spellcasting","divine-domain"]},{"level":2,"features":["channel-divinity","divine-domain-feature"]}]'::jsonb, 'Clase divina que combina magia de apoyo, curacion y presencia marcial basica.', 'Seed inicial basada en reglas basicas oficiales. La preparacion completa de conjuros y dominios se modelara de forma incremental.', '[{"type":"proficiency","proficiencyType":"armor","value":"light-armor"},{"type":"proficiency","proficiencyType":"armor","value":"medium-armor"},{"type":"proficiency","proficiencyType":"armor","value":"shields"},{"type":"proficiency","proficiencyType":"weapon","value":"simple-weapons"},{"type":"proficiency","proficiencyType":"saving_throw","value":"wisdom"},{"type":"proficiency","proficiencyType":"saving_throw","value":"charisma"},{"type":"choose_proficiency","proficiencyType":"skill","count":2,"options":["history","insight","medicine","persuasion","religion"]},{"type":"feature","featureId":"spellcasting"},{"type":"feature","featureId":"divine-domain"},{"type":"feature","featureId":"channel-divinity"}]'::jsonb, true)
on conflict do nothing;

insert into subclasses (owner_user_id, source_id, visibility, class_slug, slug, name, summary, description, granted_spells_by_level, features, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'clerigo', 'life-domain', 'Life Domain', 'Dominio clerical centrado en curacion, vitalidad y proteccion de la vida.', 'Seed inicial derivado de reglas basicas oficiales. Mantener la redaccion mecanica breve y ampliar solo tras validar el modelo del catalogo.', '[{"level":1,"spellSlugs":["bless","cure-wounds"]},{"level":3,"spellSlugs":["lesser-restoration","spiritual-weapon"]},{"level":5,"spellSlugs":["beacon-of-hope","revivify"]},{"level":7,"spellSlugs":["death-ward","guardian-of-faith"]},{"level":9,"spellSlugs":["mass-cure-wounds","raise-dead"]}]'::jsonb, '[{"level":1,"name":"Bonus Proficiency","summary":"Ganas competencia con armadura pesada.","mechanics":[{"type":"proficiency","proficiencyType":"armor","value":"heavy-armor"}]},{"level":1,"name":"Disciple of Life","summary":"Tus conjuros de curacion recuperan puntos de golpe adicionales.","mechanics":[{"type":"note","text":"When you use a spell of 1st level or higher to restore hit points, add 2 + the spell level."}]},{"level":2,"name":"Channel Divinity: Preserve Life","summary":"Canalizas energia curativa para repartir puntos de golpe entre criaturas cercanas.","mechanics":[{"type":"note","text":"Restore hit points equal to five times your cleric level, divided among creatures within 30 feet, up to half their maximum hit points."}]}]'::jsonb, '[{"type":"proficiency","proficiencyType":"armor","value":"heavy-armor"},{"type":"feature","featureId":"bonus-proficiency"},{"type":"feature","featureId":"disciple-of-life"},{"type":"feature","featureId":"preserve-life"}]'::jsonb, true)
on conflict do nothing;

insert into spells (owner_user_id, source_id, visibility, slug, name, level, school, casting_time, range_text, components, materials, duration, concentration, ritual, class_slugs, summary, description, mechanics, is_system_content)
values
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'bless', 'Bless', 1, 'enchantment', '1 action', '30 feet', 'V, S, M', 'A sprinkling of holy water.', 'Up to 1 minute', true, false, array['clerigo']::text[], 'Hasta tres criaturas suman 1d4 a tiradas de ataque y salvacion.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'cure-wounds', 'Cure Wounds', 1, 'evocation', '1 action', 'Touch', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Una criatura que tocas recupera puntos de golpe.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'lesser-restoration', 'Lesser Restoration', 2, 'abjuration', '1 action', 'Touch', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Elimina una enfermedad o una condicion de una criatura.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'spiritual-weapon', 'Spiritual Weapon', 2, 'evocation', '1 bonus action', '60 feet', 'V, S', null, '1 minute', false, false, array['clerigo']::text[], 'Creas un arma espectral que ataca como accion adicional.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'beacon-of-hope', 'Beacon of Hope', 3, 'abjuration', '1 action', '30 feet', 'V, S', null, 'Up to 1 minute', true, false, array['clerigo']::text[], 'Las criaturas elegidas ganan ventaja a sabiduria y muerte, y reciben curacion maxima.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'revivify', 'Revivify', 3, 'necromancy', '1 action', 'Touch', 'V, S, M', 'Diamonds worth 300 gp, which the spell consumes.', 'Instantaneous', false, false, array['clerigo']::text[], 'Devuelve a la vida a una criatura muerta hace poco.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'death-ward', 'Death Ward', 4, 'abjuration', '1 action', 'Touch', 'V, S', null, '8 hours', false, false, array['clerigo']::text[], 'Protege a una criatura contra un golpe mortal o un efecto letal.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'guardian-of-faith', 'Guardian of Faith', 4, 'conjuration', '1 action', '30 feet', 'V', null, '8 hours', false, false, array['clerigo']::text[], 'Un guardian espectral inflige dano radiante a enemigos cercanos.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'mass-cure-wounds', 'Mass Cure Wounds', 5, 'evocation', '1 action', '60 feet', 'V, S', null, 'Instantaneous', false, false, array['clerigo']::text[], 'Varias criaturas elegidas recuperan puntos de golpe.', null, '[]'::jsonb, true),
	(null, (select id from content_sources where code = 'srd-5-1'), 'public', 'raise-dead', 'Raise Dead', 5, 'necromancy', '1 hour', 'Touch', 'V, S, M', 'A diamond worth at least 500 gp, which the spell consumes.', 'Instantaneous', false, false, array['clerigo']::text[], 'Devuelve a la vida a una criatura fallecida hace no demasiado tiempo.', null, '[]'::jsonb, true)
on conflict do nothing;
